"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import error as components_error
from ...models.components import order as components_order
from ...models.components import order_input as components_order_input
from typing import List, Optional


@dataclasses.dataclass
class CreateOrderRequest:
    request_body: List[components_order_input.OrderInput] = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    callback_url: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'callback_url', 'style': 'form', 'explode': True }})
    r"""The url to call when the order is updated."""
    



@dataclasses.dataclass
class CreateOrderResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""An unknown error occurred interacting with the API."""
    order: Optional[components_order.Order] = dataclasses.field(default=None)
    r"""The order was created successfully."""
    

